proto < ../proto/depot.proto

### BuyShares
GRPC raynkami-balance-server.sliplane.app:50051/Depot/BuyShares
{"count": 10, "pricePerShare": 2.0, "symbol": "AAPL"}
###


### SellShares
GRPC raynkami-balance-server.sliplane.app:50051/Depot/SellShares
{
    "count": 10, 
    "pricePerShare": 2.0, 
    "symbol": "AAPL"
}


###Withdraw
GRPC raynkami-balance-server.sliplane.app:50051/Depot/Withdraw
{"amount": 100.0}

###Deposit
GRPC raynkami-balance-server.sliplane.app:50051/Depot/Deposit
{"amount": 100.0}


###GetState
GRPC raynkami-balance-server.sliplane.app:50051/Depot/GetState
{}

###GetGain
GRPC raynkami-balance-server.sliplane.app:50051/Depot/GetGain
{}

###GetShareBalance
GRPC raynkami-balance-server.sliplane.app:50051/Depot/GetShareBalance
{"symbol": "AAPL"}

###GetTransactions
GRPC raynkami-balance-server.sliplane.app:50051/Depot/GetTransactions
{"symbol": "AAPL"}
